# Generated by Django 5.0.6 on 2024-06-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_remove_habit_duration_remove_habit_linked_habit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_to",
                to="mainapp.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
