# Generated by Django 5.0.6 on 2024-06-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_habit_is_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_sent_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
